### PR TITLE
Update Qt5 to 5.10.1 and enable Qt5 build.

### PR DESCRIPTION
**Pull request by rryan**
* Disable openssl in Qt5 in favor of securetransport.
* Build sqlite as a static library only, since the Qt5 build fails if a dylib is present.

### CODE REVIEW

**Comment by Be-ing** [comment]
This is targeted at the 2.1 branch. The 2.2 branch does not yet exist.

**Comment by rryan** [comment]
2.2.x-unix didn't exist until just now when I created it from 2.1.x-unix. Re-targeted.

**Comment by rryan** [comment]
(Just for testing the environment build for now)

**Comment by rryan** [comment]
test this please

**Comment by rryan** [comment]
test this please

**Comment by rryan** [comment]
test this please

**Comment by rryan** [comment]
Successful build contains both Qt4 and Qt5: http://downloads.mixxx.org/builds/buildserver/2.2.x-macosx/prs/2.2-PR34-j00009-684db7d-osx10.7-x86_64-release.tar.gz

**Comment by Be-ing** [comment]
Thanks for taking care of this!

**Pull request merged**
