### PR TITLE
Added libmodplug-dev and updated the known distro list

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by uklotzde** [comment]
LGTM. With some unrelated changes that were not included in #79.

Let's give it a try, because the build is not working since 2 weeks ago.

**Comment by uklotzde** [comment]
How do we deal with the 2.3.x-unix branch? Cherry pick these commits or merge the whole branch?

**Comment by daschuer** [comment]
Merge, if it works without any hassle.

**Comment by rryan** [comment]
> Let's give it a try, because the build is not working since 2 weeks ago.

Which build isn't working?

**Comment by rryan** [comment]
The Ubuntu build environments are not automated unfortunately -- I kicked off an update of the pbuilder environments on my Ubuntu builder with this change. @Pegasus-RPG will need to as well.

**Pull request merged**
