### PR TITLE
Update mac env to qt 5.12

### PR DESCRIPTION
**Pull request by ferranlala**

### CODE REVIEW

**Comment by Be-ing** [comment]
add to whitelist

**Comment by Be-ing** [comment]
test this please

**Comment by ferranlala** [comment]
I don't understand why this failed.

**Comment by Be-ing** [comment]
Looks like a transient network problem:
```
+ tar -C environment -czf 2.3-PR73-j00004-8fbc9997-osx10.11-x86_64-release.tar.gz 2.3-PR73-j00004-8fbc9997-osx10.11-x86_64-release
SSH: Connecting from host [Mixxxs-iMac.local]
SSH: Connecting with configuration [downloads.mixxx.org] ...
ERROR: java.io.IOException: Unexpected EOF
Build step 'Send build artifacts over SSH' changed build result to UNSTABLE
Finished: UNSTABLE
```
https://builds.renegadetech.mixxx.org/job/v2.3/job/buildserver-2.3.x-macosx-prs/architecture=amd64,only_buildserver_capable_nodes=buildserver,platform=macosx/4/console

**Comment by Be-ing** [comment]
test this please

**Comment by Be-ing** [comment]
Build passed

**Pull request merged**
