### PR TITLE
[2.3.x-windows] Update to Qt 5.12.3

### PR DESCRIPTION
**Pull request by Be-ing**
to match macOS environment

### CODE REVIEW

**Comment by Be-ing** [comment]
Build failed:
```
ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.
```
:confused:

**Comment by daschuer** [comment]
https://bugreports.qt.io/browse/QTBUG-61291
"emoving config.cache solved the problem"

Can this be your issue as well?

**Comment by uklotzde** [comment]
@Be-ing Could you please try updating this to 5.12.4?

**Comment by Be-ing** [comment]
Have we updated macOS to 5.12.4? I'd prefer to keep the same version between OSs.

**Comment by Be-ing** [comment]
closing in favor of #83

**Pull request closed without merging**
