### PR TITLE
update Qt to 5.11.1

### PR DESCRIPTION
**Pull request by Be-ing**
Qt 5.11 has some fixes for high DPI support on Windows

### CODE REVIEW

**Comment by Be-ing** [comment]
Closed and reopened to retrigger build server...

**Comment by ywwg** [comment]
why does this keep opening and closing?

**Comment by Be-ing** [comment]
To retrigger the build server. I tried using the Jenkins function to rerun old builds but it wasn't working.

**Comment by ywwg** [comment]
> To retrigger the build server. I tried using the Jenkins function to rerun old builds but it wasn't working.

carry on :)

**Comment by Be-ing** [comment]
Builds passed:
[64 bit](https://builds.renegadetech.mixxx.org/job/v2.2/job/buildserver-2.2.x-windows-prs/38/architecture=amd64,only_buildserver_capable_nodes=buildserver,platform=windows,release_type=ReleaseFastbuild/)
[32 bit](https://builds.renegadetech.mixxx.org/job/v2.2/job/buildserver-2.2.x-windows-prs/architecture=i386,only_buildserver_capable_nodes=buildserver,platform=windows,release_type=ReleaseFastbuild/39/) (previous build failed but succeeded after manually clearing the Jenkins workspace)

**Comment by rryan** [comment]
Hm you should be able to say "test this please" to trigger a jenkins
rebuild.

**Comment by Be-ing** [comment]
Okay, good to know for the future. Are those commands documented somewhere?

**Comment by rryan** [comment]
We can customize the regex for each command but we haven't:
https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by rryan** [comment]
Question about the taglib 1.11 diffs: Did you `git mv` taglib-1.10 to taglib-1.11 and then merge in the 1.11 changes or is this just git trying to auto-detect moves?

**Comment by Be-ing** [comment]
I did not use `git mv`. I deleted the taglib-1.10 directory then added taglib-1.11.1.

**Pull request merged**
